### ISSUE TITLE
Version 2.0.0 or 1.2.0?

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/password_lock#1]
When https://github.com/defuse/php-encryption/pull/57 is reviewed and merged, we should refactor to use the encryption library with its PSR-4 namespaces.

**Comment by paragonie-scott** [comment]
I think we can declare this v2.0.0 at that point...

**Comment by defuse** [comment]
Yes, we're breaking the API so according to http://semver.org/ it should be v2.0.0.
