### ISSUE TITLE
How to get the value of $key ?

### ISSUE THREAD

**Issue by AG0001** [paragonie/password_lock#14]
$key = Key::createNewRandomKey() .
I tried to store the encrypted password and the value of $key in to the database , but failed . Just found " private 'key_bytes' => string ......" .
So, how to get the value of $key ?

**Comment by paragonie-scott** [comment]
Why would you want to store the key in the same place as the ciphertext? That's a dangerous decision that totally defeats the security of the encryption.

Instead, you should have one key that isn't stored on the same *hardware* as the database server, let alone *in* the database server.

Anyway: https://github.com/defuse/php-encryption/blob/master/docs/classes/Key.md#savetoasciisafestring and https://github.com/defuse/php-encryption/blob/master/docs/classes/Key.md#keyloadfromasciisafestringsaved_key_string-do_not_trim--false are the answers here.

**Comment by AG0001** [comment]
Thank you .

**Comment by majidramzani** [comment]
> Why would you want to store the key in the same place as the ciphertext? That's a dangerous decision that totally defeats the security of the encryption.
> 
> Instead, you should have one key that isn't stored on the same _hardware_ as the database server, let alone _in_ the database server.
> 
> Anyway: https://github.com/defuse/php-encryption/blob/master/docs/classes/Key.md#savetoasciisafestring and https://github.com/defuse/php-encryption/blob/master/docs/classes/Key.md#keyloadfromasciisafestringsaved_key_string-do_not_trim--false are the answers here.

You mean one key for application? for example  one key as website user_key and all user passwords will encrypt with that key?
