### ISSUE TITLE
Class 'ParagonIE\ConstantTime\Base64' not found

### ISSUE THREAD

**Issue by majidramzani** [paragonie/password_lock#16]
Class 'ParagonIE\ConstantTime\Base64' not found in C:\wamp64\www\password_lock\src\PasswordLock.php on line 26

**Comment by paragonie-security** [comment]
This is a Composer-specified dependency. Run `composer install` to install dependencies.

https://github.com/paragonie/password_lock/blob/31de911f8ba99e8f45139c683bbae5b570ef129f/composer.json#L33
