### ISSUE TITLE
Cannot install via composer

### ISSUE THREAD

**Issue by brezuicabogdan** [paragonie/password_lock#2]
Hi, I tried installing the package via Composer but it seems there is a versioning conflict with the required paragonie/password_lock ^2.0. The current dev-master of paragonie/password_lock is 2.0.0 but composer sees it as dev-master and cannot resolve dependecies. I am unable to install this library without composer so please update with a fix.
Thank you

**Comment by paragonie-scott** [comment]
2.0.0 is not released yet, as it depends on https://github.com/defuse/php-encryption 2.0.0 which is also not released. For now, use 1.1.0

**Comment by paragonie-scott** [comment]
This should now be fixed.
