### ISSUE TITLE
3.0.2 contains BC breaks!

### ISSUE THREAD

**Issue by chrisemerson** [paragonie/password_lock#22]
For some reason 3.0.2 was released with BC breaks - 3.0.1 is allowed to be installed on PHP v8, but 3.0.2 restricts this back down to v7 and its minor versions again. I don't know if its a goal of the project to follow semantic versioning or not but if so this shouldn't have happened.

**Comment by paragonie-security** [comment]
That looks like an erroneous tag. We'll release `v3.0.3` and delete `v3.0.2`.
