### ISSUE TITLE
Is `Binary::safeStrlen($aesKey)` needed if we are looking at bytes not characters.

### ISSUE THREAD

**Issue by void-azure** [paragonie/password_lock#25]
The `strlen` method might be fine because strlen looks at bytes not characters.

https://github.com/paragonie/password_lock/blob/86bed0c25eed864dd4d44fec19ec2abfce5c6658/src/PasswordLock.php#L84-L86

**Comment by paragonie-security** [comment]
https://www.php.net/manual/en/mbstring.overload.php

**Comment by void-azure** [comment]
Ah ok.
