### ISSUE TITLE
Why is sha256 used instead of sha512?

### ISSUE THREAD

**Issue by Zegnat** [paragonie/password_lock#3]
As this library was “motivated” by @ircmaxell’s [Security Issue: Combining Bcrypt With Other Hash Functions](http://blog.ircmaxell.com/2015/03/security-issue-combining-bcrypt-with.html) I was surprised to see it use `sha256` rather than `sha512` as the latter seems to be the only one used in the “safe” example:

> In fact, [Mozilla’s system](https://blog.mozilla.org/webdev/2012/06/08/lets-talk-about-password-storage/), which is basically `password_hash(base64_encode(hash_hmac("sha512", $password, $key, true)), PASSWORD_BCRYPT)`, is safe because it base64 encodes the raw salt.

Additionally [this StackOverflow answer](http://stackoverflow.com/a/16597402/3225372) by @ircmaxell regarding bcrypt with 72+ character passwords also seems to suggest `sha512`:

> However, `sha256` only provides `256` bits of entropy in the first place. So you're effectively cutting a possible 576 bits down to 256 bits. Your hash step *immediately*, by very definition loses **at least** 50% of the *possible* entropy in the password.
> 
> You could partially solve this by switching to `SHA512`, where you'd only reduce the available entropy by about 12%.

Is there a specific reason password_lock uses `sha256`? Am I just completely misinterpreting what Anthony has written? I’d love to get that cleared up!

**Comment by paragonie-scott** [comment]
> Is there a specific reason password_lock uses sha256?

Nope. I appear to have made a mistake.

**Comment by Zegnat** [comment]
:+1: Happy to see this will be fixed in time for the 2.0.0 release.

**Comment by ircmaxell** [comment]
Eih, 256 bits of entropy is fine for a password. That is way outside of
guess ability anyway. If we were designing from scratch, sure, 512 is
measurably better. But given that this is already in use in the wild, I
wouldn't worry about creating migration pain just for the extra entropy...

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/password_lock/blob/master/src/PasswordLock.php#L41-L56

Already added a migration path when I switched it over. The 2.0.0 release is going to use defuse/php-encryption's 2.0.0 ciphertext format anyway.
