### ISSUE TITLE
Problems when installed via composer

### ISSUE THREAD

**Issue by clayfreeman** [paragonie/password_lock#5]
When running `composer require paragonie/password_lock`, the package is installed properly in my project, but when running composer's `vendor/autoload.php`, a fatal error is encountered:

<pre>
PHP Fatal error:  require_once(): Failed opening required 'vendor/autoload.php' in /path/to/project/vendor/paragonie/password_lock/autoload.php on line 39
</pre>

I would suggest removing the autoload directive in `composer.json` and replacing it with something akin to what other projects on Packagist use.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/password_lock/blob/master/composer.json#L26-L30

Yeah, that does need to be axed.

**Comment by clayfreeman** [comment]
Thanks for taking a look at this!  Very much appreciated.  Will there be a release soon, or should I switch to the dev edition on composer?

**Comment by paragonie-scott** [comment]
It depends on https://github.com/defuse/php-encryption/tree/v2.0 which hasn't been audited or released yet. Tentative goal is January 1, however.

**Comment by clayfreeman** [comment]
Alright, I'll keep my eyes peeled.  Thanks again.
