### ISSUE TITLE
autoload.php change breaks v1.x library usage

### ISSUE THREAD

**Issue by glensc** [paragonie/password_lock#6]
https://github.com/paragonie/password_lock/commit/0bba3b8b72f0c247e0549dfce43e024cda6040f1

this change breaks projects which use subdirs, sadly the commit does not explain at all why the change  was made, could be even accidental commit.

anyway this commit makes 1.1.0 version unusable as the `vendor/autoload.php` is loaded from:
a) include path
b) relative to php script

thus, if my project structure is:
\htdocs\index.php
\htdocs\manage\index.php

it will require these paths and fail with fatal error:
\htdocs\vendor\autoload.php
\htdocs\manage\vendor\autoload.php

besides, library autoloader must not try to init some kind of global autoloader. 

please revert this and make bugfix release for v1.x series

**Comment by paragonie-scott** [comment]
> https://github.com/paragonie/password_lock/commit/0bba3b8b72f0c247e0549dfce43e024cda6040f1a

`HTTP/1.1 404 Not Found` :(

**Comment by glensc** [comment]
corrected. not sure what was wrong with the previous link

**Comment by paragonie-scott** [comment]
Is this fixed in v2.0.0 or v3.0.0?

**Comment by paragonie-scott** [comment]
v2.0.1 / v3.0.1 should no longer be affected by this.
